hostconfig:
  dns: 192.168.2.1
  tod: 216.239.35.0
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "my.local.com"
blocks:
  - netmask: 255.255.252.0
    gateway: 172.16.23.254
    ips:
    - ip: 192.168.2.41
      hostname: user-host1
    - ip: 172.16.20.42
      hostname: user-host2
    - ip: 172.16.20.43
      hostname: user-host3
