---

# vmware vCenter server config
vcenter:
  version: 6.5
  name: Embedded-vCenter-Server-Appliance
  ip_address: 192.168.2.5
  dns_servers: 192.168.2.1
  subnet_prefix: 24
  gateway: 192.168.2.1
  system_name: 192.168.2.5
  os_password: C!sc0123
  sso_password: C!sc0123
  sso_domain_name: vsphere.local
  sso_site_name: mysite
  esxi_host:
    kvm_vm_name: esxi1
    hostname: 192.168.2.6
    http_port: 80
    username: root
    password: cisco123
    deployment_network: VM Network
    datastore: datastore1
  vcenter_config:
    datacenter_name: Datacenter
    esxi_cluster:
      cluster_name: New cluster
      enable_drs: true
      enable_ha: true
      enable_vsan: true
      esxi_hosts:     
        - kvm_vm_name: esxi1
        - kvm_vm_name: esxi2
        - kvm_vm_name: esxi3
    distributed_virtual_switch:
      dvs_name: DSwitch
      esxi_hosts:
        - kvm_vm_name: esxi1
          vmnics:
            - vmnic1
            - vmnic2
        - kvm_vm_name: esxi2
          vmnics:
            - vmnic1
            - vmnic2
        - kvm_vm_name: esxi3
          vmnics:
            - vmnic1
            - vmnic2







