---

kvm_virtual_machines:
  - kvm_host: 192.168.1.114
    virtual_machines:
      - name: esxi1
        action: create
        installation_mode: pxe
        ram: 20480
        vcpus: 8
        disk_size: 400
        os: esxi6.5
        netwrok_connections:
          - network: pxe_network
            pxe_boot_interface: true
            mac_addr: 52:54:00:4b:55:f4  # MAC Address is mandatory for host specific pxe boot process
          - network: vmware_internal_mgmt_nw
          - network: vmware_external_vm_nw
          - network: vmware_internal_vm_nw
        pxe_boot_config:
          pxe_os: esxi6.5
          host_name: esxi1
          root_password: cisco123
          ip_addr: 192.168.2.6
          net_mask: 255.255.255.0
          gateway: 192.168.2.1
          dns_server: 192.168.2.1
          register_this_esxi_on_vcenter: true    # Property only applicable for ESXi hosts. Set as 'true' if you want to register it on vCenter
    
      - name: esxi2
        action: create
        installation_mode: pxe
        ram: 20480
        vcpus: 8
        disk_size: 400
        os: esxi6.5
        netwrok_connections:
          - network: pxe_network
            pxe_boot_interface: true
            mac_addr: 52:54:00:4b:55:f5 # MAC Address is mandatory for host specific pxe boot process
          - network: vmware_internal_mgmt_nw
          - network: vmware_external_vm_nw
          - network: vmware_internal_vm_nw
        pxe_boot_config:
          pxe_os: esxi6.5
          host_name: esxi2
          root_password: cisco123
          ip_addr: 192.168.2.7
          net_mask: 255.255.255.0
          gateway: 192.168.2.1
          dns_server: 192.168.2.1
          register_this_esxi_on_vcenter: true    # Property only applicable for ESXi hosts. Set as 'true' if you want to register it on vCenter

      - name: esxi3
        action: create
        installation_mode: pxe
        ram: 20480
        vcpus: 8
        disk_size: 400
        os: generic
        netwrok_connections:
          - network: pxe_network
            pxe_boot_interface: true
            mac_addr: 52:54:00:4b:55:35  # MAC Address is mandatory for host specific pxe boot process
          - network: vmware_internal_mgmt_nw
          - network: vmware_external_vm_nw
          - network: vmware_internal_vm_nw
        pxe_boot_config:
          pxe_os: esxi6.5
          host_name: esxi3
          root_password: cisco123
          ip_addr: 192.168.2.8
          net_mask: 255.255.255.0
          gateway: 192.168.2.1
          dns_server: 192.168.2.1      
          register_this_esxi_on_vcenter: true    # Property only applicable for ESXi hosts. Set as 'true' if you want to register it on vCenter


      - name: esxi4
        action: create
        installation_mode: pxe
        ram: 20480
        vcpus: 8
        disk_size: 100
        os: generic
        netwrok_connections:
          - network: pxe_network
            pxe_boot_interface: true
            mac_addr: 52:54:00:4b:25:35  # MAC Address is mandatory for host specific pxe boot process
          - network: vmware_internal_mgmt_nw
          - network: vmware_external_vm_nw
          - network: vmware_internal_vm_nw
        pxe_boot_config:
          pxe_os: esxi6.5
          host_name: esxi4
          root_password: cisco123
          ip_addr: 192.168.2.9
          net_mask: 255.255.255.0
          gateway: 192.168.2.1
          dns_server: 192.168.2.1      
          register_this_esxi_on_vcenter: true  